import path from 'node:path';
import { groupChapters, type CourseChapter, type CourseDefinition } from '../types';

const chapters: CourseChapter[] = [
  {
    id: '1',
    title: 'AI 3D技术概述与课程导入',
    navLabel: 'Ch1 AI 3D技术概述',
    summary: '建立AI 3D建模的整体认知框架，了解技术趋势与工具生态。',
    readTime: '约45分钟阅读',
    icon: '🎯',
    badgeClass: 's1',
    groupId: 'foundation',
    groupLabel: '基础入门篇',
    sourceFile: 'ch1.html',
  },
  {
    id: '2',
    title: 'AI 3D建模工具实操入门',
    navLabel: 'Ch2 AI建模工具实操',
    summary: '掌握主流AI 3D建模工具的基本操作与核心功能。',
    readTime: '约50分钟阅读',
    icon: '🛠️',
    badgeClass: 's2',
    groupId: 'foundation',
    groupLabel: '基础入门篇',
    sourceFile: 'ch2.html',
  },
  {
    id: '3',
    title: '3D模型设计原理与流程',
    navLabel: 'Ch3 设计原理与流程',
    summary: '理解设计思维、草图绘制、结构优化与轻量化处理。',
    readTime: '约45分钟阅读',
    icon: '✏️',
    badgeClass: 's3',
    groupId: 'foundation',
    groupLabel: '基础入门篇',
    sourceFile: 'ch3.html',
  },
  {
    id: '4',
    title: '材质与纹理处理技术',
    navLabel: 'Ch4 材质与纹理处理',
    summary: '掌握材质库使用、AI纹理生成、纹理映射与坐标调整。',
    readTime: '约40分钟阅读',
    icon: '🎨',
    badgeClass: 's4',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch4.html',
  },
  {
    id: '5',
    title: '渲染技术与输出设置',
    navLabel: 'Ch5 渲染技术',
    summary: '学习渲染引擎选择、光照设置、参数优化与多格式输出。',
    readTime: '约45分钟阅读',
    icon: '💡',
    badgeClass: 's5',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch5.html',
  },
  {
    id: '6',
    title: '实体生产工艺实践',
    navLabel: 'Ch6 实体生产工艺',
    summary: '3D打印、CNC加工、注塑成型的原理与实操流程。',
    readTime: '约50分钟阅读',
    icon: '🏭',
    badgeClass: 's6',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch6.html',
  },
  {
    id: '7',
    title: '综合项目实战：基础项目',
    navLabel: 'Ch7 基础综合项目',
    summary: '完成第一个从设计到实体生产的完整项目。',
    readTime: '约60分钟阅读',
    icon: '🚀',
    badgeClass: 's7',
    groupId: 'project',
    groupLabel: '项目实战篇',
    sourceFile: 'ch7.html',
  },
  {
    id: '8',
    title: '毕业项目与技能认证',
    navLabel: 'Ch8 毕业项目',
    summary: '完成复杂产品的全流程设计与实体生产，获取技能认证。',
    readTime: '约60分钟阅读',
    icon: '🎓',
    badgeClass: 's8',
    groupId: 'project',
    groupLabel: '项目实战篇',
    sourceFile: 'ch8.html',
  },
];

export const ai3DManufacturingCourse: CourseDefinition = {
  slug: 'ai-3d-manufacturing',
  title: 'AI 3D建模与实体生产完全指南',
  subtitle: '从0开始利用AI技术设计制作3D模型并实现实体生产',
  description:
    '零基础学习者能够系统掌握AI 3D建模技能，从创意构思到实体生产全流程覆盖。',
  icon: '🎨',
  sourceRoot: path.resolve(process.cwd(), 'src/course-sources/ai-3d-manufacturing/chapters'),
  storageKey: 'ai-3d-manufacturing-course-progress',
  chapters,
  groups: groupChapters(chapters),
};