import path from 'node:path';
import { groupChapters, type CourseChapter, type CourseDefinition } from '../types';

const chapters: CourseChapter[] = [
  {
    id: '1',
    title: '传感器融合概论：让无人机“看见”真实世界',
    navLabel: 'Ch1 传感器融合概论',
    summary: '建立传感器融合的宏观认知。',
    readTime: '约35分钟阅读',
    icon: '📡',
    badgeClass: 's1',
    groupId: 'part1',
    groupLabel: 'Part I · 基础概念',
    sourceFile: 'ch1.html',
  },
  {
    id: '2',
    title: '无人机平台与系统架构',
    navLabel: 'Ch2 无人机平台与系统架构',
    summary: '理解无人机平台与感知约束。',
    readTime: '约30分钟阅读',
    icon: '🛸',
    badgeClass: 's2',
    groupId: 'part1',
    groupLabel: 'Part I · 基础概念',
    sourceFile: 'ch2.html',
  },
  {
    id: '3',
    title: '相机与计算机视觉',
    navLabel: 'Ch3 相机与计算机视觉',
    summary: '从针孔模型到视觉几何。',
    readTime: '约35分钟阅读',
    icon: '📷',
    badgeClass: 's3',
    groupId: 'part2',
    groupLabel: 'Part II · 单传感器深度',
    sourceFile: 'ch3.html',
  },
  {
    id: '4',
    title: '激光雷达原理与点云',
    navLabel: 'Ch4 激光雷达原理与点云',
    summary: '点云几何与运动畸变。',
    readTime: '约35分钟阅读',
    icon: '💨',
    badgeClass: 's4',
    groupId: 'part2',
    groupLabel: 'Part II · 单传感器深度',
    sourceFile: 'ch4.html',
  },
  {
    id: '5',
    title: 'IMU与惯性导航',
    navLabel: 'Ch5 IMU与惯性导航',
    summary: '惯导误差、积分漂移与姿态更新。',
    readTime: '约35分钟阅读',
    icon: '⚙️',
    badgeClass: 's5',
    groupId: 'part2',
    groupLabel: 'Part II · 单传感器深度',
    sourceFile: 'ch5.html',
  },
  {
    id: '6',
    title: 'GPS与卫星导航',
    navLabel: 'Ch6 GPS与卫星导航',
    summary: '绝对定位与RTK增强。',
    readTime: '约30分钟阅读',
    icon: '🛰️',
    badgeClass: 's6',
    groupId: 'part2',
    groupLabel: 'Part II · 单传感器深度',
    sourceFile: 'ch6.html',
  },
  {
    id: '7',
    title: '时间同步与空间标定',
    navLabel: 'Ch7 时间同步与空间标定',
    summary: '让不同传感器在同一时空对齐。',
    readTime: '约30分钟阅读',
    icon: '🔗',
    badgeClass: 's7',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch7.html',
  },
  {
    id: '8',
    title: '概率滤波理论',
    navLabel: 'Ch8 概率滤波理论',
    summary: '不确定性、贝叶斯更新和状态估计。',
    readTime: '约35分钟阅读',
    icon: '📊',
    badgeClass: 's8',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch8.html',
  },
  {
    id: '9',
    title: '卡尔曼滤波与EKF/UKF',
    navLabel: 'Ch9 卡尔曼滤波与EKF/UKF',
    summary: '在线估计的核心工具箱。',
    readTime: '约40分钟阅读',
    icon: '🔄',
    badgeClass: 's9',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch9.html',
  },
  {
    id: '10',
    title: '因子图与非线性优化',
    navLabel: 'Ch10 因子图与非线性优化',
    summary: '用约束图描述多传感器状态。',
    readTime: '约40分钟阅读',
    icon: '🔗',
    badgeClass: 's10',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch10.html',
  },
  {
    id: '11',
    title: '视觉惯性融合(VIO)',
    navLabel: 'Ch11 视觉惯性融合(VIO)',
    summary: '视觉与IMU紧耦合估计。',
    readTime: '约40分钟阅读',
    icon: '👁️',
    badgeClass: 's11',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch11.html',
  },
  {
    id: '12',
    title: '激光雷达视觉融合',
    navLabel: 'Ch12 激光雷达视觉融合',
    summary: '几何信息与视觉信息互补。',
    readTime: '约35分钟阅读',
    icon: '💨',
    badgeClass: 's12',
    groupId: 'part3',
    groupLabel: 'Part III · 融合算法',
    sourceFile: 'ch12.html',
  },
  {
    id: '13',
    title: '融合定位与建图',
    navLabel: 'Ch13 融合定位与建图',
    summary: '形成可用的位姿与地图。',
    readTime: '约35分钟阅读',
    icon: '🎯',
    badgeClass: 's13',
    groupId: 'part4',
    groupLabel: 'Part IV · 应用与部署',
    sourceFile: 'ch13.html',
  },
  {
    id: '14',
    title: '路径规划与避障',
    navLabel: 'Ch14 路径规划与避障',
    summary: '把感知结果转化为飞行决策。',
    readTime: '约30分钟阅读',
    icon: '🗺️',
    badgeClass: 's14',
    groupId: 'part4',
    groupLabel: 'Part IV · 应用与部署',
    sourceFile: 'ch14.html',
  },
  {
    id: '15',
    title: '集群协同感知',
    navLabel: 'Ch15 集群协同感知',
    summary: '多机共享感知与协同决策。',
    readTime: '约30分钟阅读',
    icon: '👥',
    badgeClass: 's15',
    groupId: 'part4',
    groupLabel: 'Part IV · 应用与部署',
    sourceFile: 'ch15.html',
  },
  {
    id: '16',
    title: '嵌入式部署与加速',
    navLabel: 'Ch16 嵌入式部署与加速',
    summary: '从算法到机载算力优化。',
    readTime: '约35分钟阅读',
    icon: '💻',
    badgeClass: 's16',
    groupId: 'part4',
    groupLabel: 'Part IV · 应用与部署',
    sourceFile: 'ch16.html',
  },
  {
    id: '17',
    title: '开源项目与工具链',
    navLabel: 'Ch17 开源项目与工具链',
    summary: '把知识落到可用工具和项目。',
    readTime: '约30分钟阅读',
    icon: '🛠️',
    badgeClass: 's17',
    groupId: 'part4',
    groupLabel: 'Part IV · 应用与部署',
    sourceFile: 'ch17.html',
  },
];

export const sensorFusionCourse: CourseDefinition = {
  slug: 'sensor-fusion',
  title: '无人机传感器融合完全指南',
  subtitle: '从单传感器到多传感器协同',
  description: '无人机传感器、时空标定、概率滤波与融合算法的完整教程。',
  icon: '🚀',
  sourceRoot: path.resolve(process.cwd(), 'src/course-sources/sensor-fusion/chapters'),
  storageKey: 'sensor-fusion-course-progress',
  chapters,
  groups: groupChapters(chapters),
};
