import path from 'node:path';
import { groupChapters, type CourseChapter, type CourseDefinition } from '../types';

const chapters: CourseChapter[] = [
  {
    id: '1',
    title: 'AI赋能开发综述：从创意到落地的智能新范式',
    navLabel: 'Ch1 AI赋能开发综述',
    summary: '建立AI-Augmented Development的整体认知框架。',
    readTime: '约35分钟阅读',
    icon: '🤖',
    badgeClass: 's1',
    groupId: 'foundation',
    groupLabel: '入门基础篇',
    sourceFile: 'ch1.html',
  },
  {
    id: '2',
    title: '产品思维与需求分析——用AI挖掘真实需求',
    navLabel: 'Ch2 产品思维与需求分析',
    summary: 'AI辅助需求提取、建模与优先级划分。',
    readTime: '约40分钟阅读',
    icon: '💡',
    badgeClass: 's2',
    groupId: 'foundation',
    groupLabel: '入门基础篇',
    sourceFile: 'ch2.html',
  },
  {
    id: '3',
    title: '系统架构设计——AI辅助的架构决策',
    navLabel: 'Ch3 系统架构设计',
    summary: 'AI辅助架构选型、数据建模与API设计。',
    readTime: '约45分钟阅读',
    icon: '🏗️',
    badgeClass: 's3',
    groupId: 'foundation',
    groupLabel: '入门基础篇',
    sourceFile: 'ch3.html',
  },
  {
    id: '4',
    title: '开发流程与项目管理——AI驱动的研发管理',
    navLabel: 'Ch4 项目管理与开发流程',
    summary: '敏捷 ceremonies 的AI辅助与看板优化。',
    readTime: '约40分钟阅读',
    icon: '📋',
    badgeClass: 's4',
    groupId: 'foundation',
    groupLabel: '入门基础篇',
    sourceFile: 'ch4.html',
  },
  {
    id: '5',
    title: '开发环境与工具链——AI-Ready的工程基础设施',
    navLabel: 'Ch5 开发环境与工具链',
    summary: '容器化环境、Copilot配置与代码规范。',
    readTime: '约40分钟阅读',
    icon: '🛠️',
    badgeClass: 's5',
    groupId: 'foundation',
    groupLabel: '入门基础篇',
    sourceFile: 'ch5.html',
  },
  {
    id: '6',
    title: 'AI编码助手实战——ChatGPT与Copilot的高效使用',
    navLabel: 'Ch6 AI编码助手实战',
    summary: '掌握ChatGPT和Copilot的高阶使用技巧。',
    readTime: '约45分钟阅读',
    icon: '⌨️',
    badgeClass: 's6',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch6.html',
  },
  {
    id: '7',
    title: '智能代码生成与优化——从框架到业务逻辑',
    navLabel: 'Ch7 智能代码生成与优化',
    summary: 'AI生成框架代码、业务逻辑与算法实现。',
    readTime: '约50分钟阅读',
    icon: '⚡',
    badgeClass: 's7',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch7.html',
  },
  {
    id: '8',
    title: '自动化测试与质量保障——AI驱动的测试工程',
    navLabel: 'Ch8 自动化测试与质量保障',
    summary: 'AI生成测试用例、边界测试与CI集成。',
    readTime: '约45分钟阅读',
    icon: '🧪',
    badgeClass: 's8',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch8.html',
  },
  {
    id: '9',
    title: '代码审查与缺陷预测——AI赋能的代码质量保障',
    navLabel: 'Ch9 代码审查与缺陷预测',
    summary: 'AI代码审查工具、安全漏洞检测与质量度量。',
    readTime: '约40分钟阅读',
    icon: '🔍',
    badgeClass: 's9',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch9.html',
  },
  {
    id: '10',
    title: '自动化部署与运维——AI赋能的DevOps',
    navLabel: 'Ch10 自动化部署与运维',
    summary: 'CI/CD流水线、容器化部署与智能监控。',
    readTime: '约45分钟阅读',
    icon: '🚀',
    badgeClass: 's10',
    groupId: 'core',
    groupLabel: '核心技能篇',
    sourceFile: 'ch10.html',
  },
  {
    id: '11',
    title: 'AI驱动的需求分析与文档自动化',
    navLabel: 'Ch11 需求分析与文档自动化',
    summary: 'AI生成PRD、API文档与一致性检查。',
    readTime: '约40分钟阅读',
    icon: '📝',
    badgeClass: 's11',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch11.html',
  },
  {
    id: '12',
    title: '智能项目管理——AI驱动的研发效能提升',
    navLabel: 'Ch12 智能项目管理',
    summary: '工作量估算、Sprint健康度分析与资源协调。',
    readTime: '约40分钟阅读',
    icon: '📊',
    badgeClass: 's12',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch12.html',
  },
  {
    id: '13',
    title: '低代码/无代码AI平台——快速构建AI应用',
    navLabel: 'Ch13 低代码AI平台',
    summary: 'Dataiku、Vertex AI与LangFlow实战。',
    readTime: '约45分钟阅读',
    icon: '🔧',
    badgeClass: 's13',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch13.html',
  },
  {
    id: '14',
    title: 'AI驱动的运维智能化——从监控到自愈',
    navLabel: 'Ch14 智能运维AIOps',
    summary: '异常检测、根因分析与预测性维护。',
    readTime: '约45分钟阅读',
    icon: '🎯',
    badgeClass: 's14',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch14.html',
  },
  {
    id: '15',
    title: '数据驱动的决策——AI辅助的业务分析',
    navLabel: 'Ch15 数据驱动决策',
    summary: '指标体系设计、A/B测试与数据可视化。',
    readTime: '约40分钟阅读',
    icon: '📈',
    badgeClass: 's15',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch15.html',
  },
  {
    id: '16',
    title: 'AI伦理与治理——负责任的AI开发实践',
    navLabel: 'Ch16 AI伦理与治理',
    summary: '公平性、透明度、隐私保护与EU AI Act。',
    readTime: '约40分钟阅读',
    icon: '⚖️',
    badgeClass: 's16',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch16.html',
  },
  {
    id: '17',
    title: '综合实战——构建智能化产品发布',
    navLabel: 'Ch17 综合实战',
    summary: '端到端智能化产品开发的完整旅程。',
    readTime: '约50分钟阅读',
    icon: '🎓',
    badgeClass: 's17',
    groupId: 'ai-practice',
    groupLabel: 'AI赋能实战篇',
    sourceFile: 'ch17.html',
  },
];

export const aiDevLifecycleCourse: CourseDefinition = {
  slug: 'ai-dev-lifecycle',
  title: '全周期程序开发实战指南',
  subtitle: 'AI AGENT赋能从创意到部署的全流程开发',
  description:
    '系统涵盖产品构思、架构设计、AI驱动开发、智能测试、自动化部署与运维的全链路工程实践。',
  icon: '💫',
  sourceRoot: path.resolve(process.cwd(), 'src/course-sources/ai-dev-lifecycle/chapters'),
  storageKey: 'ai-dev-lifecycle-course-progress',
  chapters,
  groups: groupChapters(chapters),
};
